Adding more content to community README to help guide folks
kubevirt/community pull request #278
Opened 2024-03-14 19:31 UTC by aburdenthehand

Fleshing out our README file with useful links to getting started, contributing guide, sig-release, community meeting, adopters file, and probably something else too.

I've added a lot of links, which have the terrible fate of changing sometimes, so I've tried to be mindful of this and link only to more robustly located things. 

**Release note**:

```release-note
NONE
```

2024-03-19 14:30 UTC, fabiand commented
/approve

@dhiller can you give this a second set of eyes?

2024-03-19 14:42 UTC, jean-edouard commented on README.md
> +Here you will find all things community, including our [membership policy](membership_policy.md), [project governance](https://github.com/kubevirt/community/blob/main/GOVERNANCE.md), charters for our
```suggestion
Here you will find all things community, including our [membership policy](membership_policy.md), [project governance](GOVERNANCE.md), charters for our SIGs (Special Interest Groups), [upcoming events](https://github.com/kubevirt/community/wiki/Events), and more.
```

2024-03-19 14:42 UTC, jean-edouard commented on README.md
> +If you're looking for the main code base, you can find it at [kubevirt/kubevirt](
Missing URL

2024-03-19 14:50 UTC, dhiller requested changes
As Jed said, we can shorten the GOVERNANCE url and add the k/kubevirt url.

2024-03-20 12:31 UTC, aburdenthehand commented
@jean-edouard Thanks for the catch!
I have updated both as requested.

2024-03-20 12:38 UTC, jean-edouard approved these changes

2024-03-20 12:39 UTC, merged